# Use the official PHP image with Apache.
FROM mysql:latest

# Install system dependencies and PHP extensions required for your application
# RUN apt-get update

# Expose port 3306 for the mysql server.
EXPOSE 3306
